[project]
name = "blightsanest-semantic-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "sentence-transformers>=5.2.2",
    "uvicorn>=0.40.0",
]
